# Generated by Django 4.2.6 on 2023-10-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='tags',
        ),
        migrations.AddField(
            model_name='quotes',
            name='tags',
            field=models.ManyToManyField(to='quotesapp.tag'),
        ),
    ]
